
classDiagram
    direction LR
    ShoppingCart --> CartItem
    class ShoppingCart {
        <<Aggregate root>>
        + Id
        + Items
        + AddItem()
    }
    class CartItem {
        + Id
        + Sku
        + Name
        + Price
        + Count
    }
